### ISSUE TITLE
Is there a way to dynamically change the list of links?

### ISSUE THREAD

**Issue by jt3k** [KittyGiraudel/react-a11y-footnotes#146]
is there a way to dynamically change the list of footnotes when the number of footnotes changes?

https://codesandbox.io/s/react-a11y-footnotes-forked-n6wiv6?file=/src/App.js

Here is an example of such an error.
if you click on toggle, the number of footnotes in the article changes, but the number of references in footnotes does not

**Comment by KittyGiraudel** [comment]
Right, so this one is a bit more complicated. That being said, I also don’t think it’s necessary. I would argue footnotes can be static, even if the user do not see all the references (because they happen to be toggled away). Additionally, content should not be inserted and removed from the DOM but hidden and shown using a disclosure pattern for it to be nicely accessible (see [react-a11y-disclosure](https://github.com/KittyGiraudel/react-a11y-disclosure) for instance). :)

**Comment by jt3k** [comment]
clear) Generally speaking, this is not an easy task. I will try to fork and solve this problem for myself. :-)

**Comment by KittyGiraudel** [comment]
Please do share if you find a nice solution!
